### PR TITLE
Add code to expose Option names and example code for use of those Option names

### PR DESCRIPTION
**Pull request by fragmental**

### CODE REVIEW

**Comment by desplesda** [comment]
This feature looks worthwhile - I'll update it to work with the most recent work in `develop`.

Tagging issue #138 so I can keep things linked.

**Comment by fragmental** [comment]
Hey, thanks!  When I saw the e-mail notification I was bracing myself for a response something like "Doesn't work with current implementation.  Closing."  I'm glad to read your response.

**Comment by desplesda** [comment]
We’ll need to adapt it for the current implementation for sure, but it’s a potentially useful feature!

**Comment by desplesda** [comment]
Done and merged! Thank you!

**Pull request merged**
