### PR TITLE
Feature/vm state save

### PR DESCRIPTION
**Pull request by desplesda**
This feature updates #208 to the most recent work done in `develop`, in preparation for merging. Thanks to @naNuke for doing this work!

* **Please check if the pull request fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated to describe this change

To update the documentation on [yarnspinner.dev](https://yarnspinner.dev), please visit the [documentation repository](https://github.com/YarnSpinnerTool/Docs).

* **What kind of change does this pull request introduce?**

- [ ] Bug Fix
- [x] Feature
- [ ] Something else

* **What is the current behavior?** (You can also link to an open issue here)

Currently, there is no way to store the state of the virtual machine, which makes it impossible to stop half-way through a dialogue and resume it later.

* **What is the new behavior (if this is a feature change)?**

This PR adds the ability to save and restore the state of a dialogue.

* **Does this pull request introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No existing APIs are changed in this PR.

* **Other information**:

n/a

### CODE REVIEW

**Comment by desplesda** [comment]
7605b6c updates this branch to latest `develop` (currently 4d7e6f3700).

Tests are failing because:

1. `StateOption` doesn't have support for substitutions (they landed in `develop` after #208 was proposed)
2. `State.CurrentNodeName` defaults to the empty string, not null (so `TestGettingCurrentNodeName` fails because expected behaviour is that `Dialogue.currentNode` return null when no node is executing).

The solution for 2. is straightforward; 1. is slightly trickier. 

A solution might be to make `OptionSet` and `Line` be serialisable into protobufs, and discard the `StateOption` class (which is a protobuf-serializable version of `OptionSet.Option`.)

@McJones and/or @naNuke , can I get your thoughts on this?

**Comment by naNuke** [comment]
I've tried to quickly familiarize myself with the relevant changes in the code so forgive me if I am stating something obvious...

It seems the culprit to problem 1. is not necessarily because StateOption doesnt support substitutions, it is afterall just a replacement for KeyValuePair class that can be serialized with protobuf. 

Its more than possible that an old piece of code has merged, I am thinking specifically line 1024 of VirtualMachine.cs (https://github.com/YarnSpinnerTool/YarnSpinner/blob/7605b6c401a12f8ce82830e2577074a81d6a20ff/YarnSpinner/VirtualMachine.cs#L1024) where new Line class is created without substitution and doesnt use Line classes created in OpCode.AddOption: case.

I would probably start there, but as I said, I would need to read more to think of a solution. Is it as easy as removing the new Line class code because they are already created in AddOption? Not sure. I will have time to investigate further later tonight (central european timezone).

**Comment by desplesda** [comment]
Ah, I think you're right - when merging the branches, I clobbered part of the code that prepares the options for delivery to the game.

**Comment by naNuke** [comment]
Hello, I am sorry for late reply, was busy with life amid the pandemic stuff.

Should I look at the merge and fix the conflicts or have someone progressed with it to some degree?

**Comment by GinIsTheAnswer** [comment]
Hey! Is this still coming in 2.0? I would like to use this feature.
Is there something I can do to help to get this included?

**Comment by McJones** [comment]
Since this PR was originally opened there have been changes to how YS and saving works.
As such while this is a worthwhile feature the addition of https://github.com/YarnSpinnerTool/YarnSpinner-Unity/pull/51 has reduced the impetus for this feature somewhat.
Additionally the issues around resolving *game* state and not *yarn* state (working out how to replay commands in particular) would I fear only lead to confusion so I think this is probably a bigger issue than we ever first assumed.

I am going to close this PR but huge thanks to naNuke for their work.

**Pull request closed without merging**
