### PR TITLE
Create a upm branch with GitHub actions

### PR DESCRIPTION
**Pull request by favoyang**
* **Please check if the pull request fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated to describe this change

To update the documentation on [yarnspinner.dev](https://yarnspinner.dev), please visit the [documentation repository](https://github.com/YarnSpinnerTool/Docs).

* **What kind of change does this pull request introduce?**

- [ ] Bug Fix
- [ ] Feature
- [x] Something else

* **What is the current behavior?** (You can also link to an open issue here)

  See #201 

* **What is the new behavior (if this is a feature change)?**

  - Add GitHub action to create upm branch
  - DLL generated within the process, thus modified the build.sh slightly to allow this happens.
  - DLL Unity meta files are stored under .github/meta, and copied to the upm branch.
  - The examples folder has been handled the UPM way (using the Unity package manager to import samples)

   You're welcome to test the result with this added to your Packages/manifest.json 
    ```
   "dev.secretlab.yarnspinner": "https://github.com/favoyang/YarnSpinner.git#upm"
   ```

* **Does this pull request introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

  No

* **Other information**:

  n/a

### CODE REVIEW

**Comment by desplesda** [comment]
Thank you for doing this!!

What information do we need to convey to our users so that they can make use of this?

**Comment by favoyang** [comment]
Like this?
- Add OpenUPM version badge to README.md 
- Tweak README.md to remove the necessity to download .unitypackage (move to next)
- Update tutorial (on the doc repository), to show how to install via UPM Git URL, OpenUPM, or the traditional .unitypackage way. 

I can prepare the docs for you. Do you prefer another PR (after everything are verified) or just update this PR?

**Comment by desplesda** [comment]
An update to this PR would be perfect!

**Comment by favoyang** [comment]
Docs updated and https://github.com/YarnSpinnerTool/Docs/pull/3 should be merged as well.

**Comment by favoyang** [comment]
TODO
- [ ] test the upm branch on my fork first.
```
# You're welcome to test the result with this added to your Packages/manifest.json

"dev.secretlab.yarnspinner": "https://github.com/favoyang/YarnSpinner.git#upm"
```
- [ ] review and merge.
- [ ] create a `upm/x.y.z` branch from the `upm` branch for the latest / next release.
- [ ] wait for OpenUPM pipelines 5-10 minutes to catch up. You will find the results at the version history section on the detail page https://openupm.com/packages/dev.secretlab.yarnspinner/

**Comment by desplesda** [comment]
@favoyang I've created the new Yarn Spinner repo at https://github.com/YarnSpinnerTool/YarnSpinner-Unity, and filed a PR on OpenUPM (https://github.com/openupm/openupm/pull/559) to update its entry. I'm intending for all tags that don't include "-beta" in them to be marked as releases; any release on `master` should go out as an update to the package. The DLL dependencies will be automatically kept up to date when this repo merges to master by external CI. Does this PR look correct for what I'm intending, and if so, can you merge it?

**Comment by favoyang** [comment]
@demanrisu looks good. The version 1.2.0 has been published.

https://openupm.com/packages/dev.secretlab.yarnspinner/

**Comment by favoyang** [comment]
Feel free to add a badge if need

https://openupm.com/packages/dev.secretlab.yarnspinner/ (badge section)

**Comment by favoyang** [comment]
The README content of the OpenUPM page will take a while (around half-hour) to catch up.

**Comment by desplesda** [comment]
Thank you very much! (I just opened a second pull request - I totally blanked on my originally intended package name, which should be `dev.yarnspinner.unity`, rather than `dev.secretlab.yarnspinner`.) Once that's merged, I think we're good to go!

**Comment by favoyang** [comment]
@desplesda please checkout this comment: https://github.com/openupm/openupm/pull/560#issuecomment-638755711

**Pull request closed without merging**
