### PR TITLE
Added a WSA version of the YarnSpinner project

### PR DESCRIPTION
**Pull request by Hexalotl**
Added a new standalone .csproj to build Yarn for Window Store Apps. Fixes issue #42.
After building YarnSpinner using this project, follow the steps found here:

http://docs.unity3d.com/Manual/windowsstore-plugins.html

For any future updates, please be careful of using reflection, type information, or file IO since WSA generally handles them differently.

### CODE REVIEW

**Comment by desplesda** [comment]
First: awesome work. Thanks for making this pull request!

Second: I notice that it's mostly replacing like-for-like API calls that aren't available on WSA, with the (single?) exception being the removal of the LoadFile method.

I'm a little dissatisfied at having two `.csproj` files that represent the same project. Given that `Loader` arguably shouldn't be doing file I/O anyway (games using Unity will never invoke it), I'm tempted to pull that method out, and instead of using `#if` to swap out the methods, just use the WSA-friendly methods.

Does that sounds like a reasonable approach?

**Comment by Dynameter** [comment]
The reason I had two seperate .csproj files is because the WSA version compiles against a special portable version of .net which I am not sure is available with xbuild. I had a previous pull request that I cancelled because I noticed that the build failed because xbuild could not find the portable libraries. I don't know much about xbuild but if you can find if it has support for these portable libraries, it would be greatly appreciated!

**Comment by desplesda** [comment]
Will take a look!

**Comment by P00TAT00** [comment]
Hey! I want to use yarn in my game, but I need the dialogue "boxes" to show whos talking with an arrow or something similar (like in night in the woods, for example) I couldn't find any tutorial on this subject, and i have no idea how to do it using yarn. if anyone here could help me, that would be awesome!

**Comment by silasary** [comment]
Normally I'd recommend targetting .NET Standard, which would allow for a single project to target both Windows Store and Desktop.

But the inclusion of a Unity dependency (and therefore .NET 3.5) means that .NET Standard isn't an option.

There are also no PCLs that would fit the requirements.

The requirement of two separate projects is unfortunately something we can't get around.

Note that this is all assuming that you're targetting UWP directly.  If you're using Unity to target UWP, I think just cleaning up the bad references should be enough. (But don't quote me on that - I've never actually tried it)

**Comment by desplesda** [comment]
Hi! Thanks for submitting this pull request, and I'm sorry that it didn't get merged. Because version 1.0 was a complete overhaul of the project, this pull request doesn't really apply anymore, so I'm closing it. Thank you again for contributing!

**Pull request closed without merging**
