### PR TITLE
Visual Novel example

### PR DESCRIPTION
**Pull request by radiatoryang**
I've merged in Ropework (https://github.com/radiatoryang/ropework) as an example, and renamed to the much less exciting but clearer "Visual Novel Example"

also cleaned it up a lot and made it more compliant with how Yarn Spinner v1.0 does things

all the code is at `/Unity/Assets/YarnSpinner/Examples/VisualNovelExample/Scripts/`

- VNDialogueUI.cs inherits from DialogueUI.cs and just overrides `RunLine()` to display character name separately from dialogue
- VNManager.cs is where all the custom Yarn commands live, where it kinda copies RenPy functionality a bit
- documentation is at `/VisualNovelExample/VisualNovel_Readme.md`

my code probably isn't the best, but it's pretty heavily commented and hopefully it shows off a lot of features

feel free to make whatever edits you want, or let me know if I should do anything

### CODE REVIEW

**Comment by naNuke** [comment]
Hello, I am not a YarnSpinner maintainer but as someone who is using it in my own project I would like to leave some comments, but take them with a grain of salt.

- While not entirely that exhausting, I think that including extra fonts and other assets directly not related to the example is not necessary. The example should be similiarly coded in complexity as the original Yarns Space example, in this case using the default unity text or default textmeshpro with default fonts.

- I think that your expanding the Yarn classes make it hard to read as a standalone example that can function out of the box. Yarn provides those classes in abstract form and users should (its better practice imo), by design, implement their own DialogueUIBehaviour and VariableStorageBehaviour. That said, those default implementations are at the moment coded towards the Space scene example.
_This might be something that Yarn could change in the future imo (to make examples clearer to understand) as the DialogueRunner should be the only class used as-is in user projects, while variable storage and dialogue ui should be custom implemented (while Yarn provides default implementation examples for activated dialogue, visual novel format, etc...)_

- Your example namespace should be Yarn.Unity.VNExample

_Just my two cents :)_

Otherwise nice work, definitelly something that YarnSpinner could use as example project.

**Comment by radiatoryang** [comment]
I hear you on the namespace and fonts issues. BUT I will point out that the Space example has forced everyone to import a 21 mb PSD for the last few years. By precedent, this VN example is less than half the size / footprint of the Space example.

re: making VNDialogueUI standalone, I disagree for these reasons:
- DialogueUI isn't called ExampleDialogueUI anymore, it's at the same level as DialogueRunner now, where many users use it as-is?... also I argue the "best practice" ship has sailed, and crashed into the iceberg that is "what users actually do"
- maintenance wise, I don't want to keep submitting PRs for fixing minor bugs in this example, and I don't want to keep updating 2 copies of the same duplicate boilerplate code when DialogueUI inevitably deviates from VNDialogueUI in the future... it creates a technical debt that I think both me, and the maintainers, would rather avoid

**Comment by unknowndevice** [comment]
Just to add. Once YarnSpinner becomes a package as described in #201 It'll be under the Samples~ folder and someone will choose to download the sample from the packages windows. In such a case I don't think the extra fonts and specifics really matter so much.

**Comment by radiatoryang** [comment]
some last cleanup, renamed VNDialogueUI to DialogueUISplit, and moved *all* VN functions to VNManager.cs, so it's a bit more modular, but unfortunately it is still inheriting from DialogueUI base

this sparked some thinking... **can we just merge this DialogueUISplit functionality into the main DialogueUI then?** IMO this is pretty standard behavior that should probably be included in Yarn Spinner by default, and then it can be disabled in the inspector by the user if they want? any thoughts?

image

**Comment by desplesda** [comment]
This functionality should be core; I'm planning on adding support for this into the parser, so that it can deliver information in the `Line` struct about the character.

**Comment by radiatoryang** [comment]
ah, ok, I guess I'll wait on this until the Line struct supports characters then?

**Comment by desplesda** [comment]
I've updated this PR to the most recent work in YarnSpinnerTool/YarnSpinner-Unity, and pushed the updated branch to the new repo. 

I'll close this PR here, and I've opened a new one on the new repo at https://github.com/YarnSpinnerTool/YarnSpinner-Unity/pull/6. Let's continue this there!

**Pull request closed without merging**
